import { NextResponse } from "next/server";

type GitHubIssue = { number: number; title: string; body: string | null; html_url: string; labels: { name: string }[]; pull_request?: unknown };
const githubBase = "https://api.github.com";

function clip(value: string, limit: number) { return value.length > limit ? `${value.slice(0, limit)}\n[truncated]` : value; }
function parseRepo(value: string) { try { const url = new URL(value); if (url.hostname !== "github.com") return null; const [owner, repo] = url.pathname.split("/").filter(Boolean); return owner && repo ? { owner, repo: repo.replace(/\.git$/, "") } : null; } catch { return null; } }
async function github(path: string) { const token = process.env.GITHUB_TOKEN; if (!token) throw new Error("The server is missing GITHUB_TOKEN. Add a GitHub personal access token and try again."); const response = await fetch(`${githubBase}${path}`, { headers: { Accept: "application/vnd.github+json", Authorization: `Bearer ${token}`, "X-GitHub-Api-Version": "2022-11-28" }, cache: "no-store" }); if (!response.ok) throw new Error(response.status === 404 ? "GitHub could not find that public repository." : `GitHub request failed (${response.status}).`); return response.json(); }
async function content(owner: string, repo: string, path: string) { try { const file = await github(`/repos/${owner}/${repo}/contents/${path}`) as { content?: string; encoding?: string }; return file.encoding === "base64" && file.content ? Buffer.from(file.content, "base64").toString("utf8") : ""; } catch { return ""; } }
async function openIssues(owner: string, repo: string) { const issues: GitHubIssue[] = []; for (let page = 1; ; page += 1) { const nextPage = await github(`/repos/${owner}/${repo}/issues?state=open&sort=updated&direction=desc&per_page=100&page=${page}`) as GitHubIssue[]; issues.push(...nextPage); if (nextPage.length < 100) return issues; } }
async function groq<T>(name: string, schema: object, developer: string, data: object): Promise<T> { const key = process.env.GROQ_API_KEY; if (!key) throw new Error("The server is missing GROQ_API_KEY."); const response = await fetch("https://api.groq.com/openai/v1/responses", { method: "POST", headers: { Authorization: `Bearer ${key}`, "Content-Type": "application/json" }, body: JSON.stringify({ model: process.env.GROQ_MODEL ?? "openai/gpt-oss-120b", instructions: developer, input: JSON.stringify(data), text: { format: { type: "json_schema", name, strict: true, schema } } }) }); const output = await response.json() as { output_text?: string; output?: { type?: string; content?: { type?: string; text?: string }[] }[]; error?: { message?: string } }; if (!response.ok) throw new Error(`Groq analysis failed (${response.status}): ${output.error?.message ?? "unknown error"}`); const structuredText = output.output_text ?? output.output?.flatMap((item) => item.content ?? []).find((item) => item.type === "output_text")?.text; if (!structuredText) throw new Error("Groq returned a completed response without output text. Try GROQ_MODEL=openai/gpt-oss-120b."); try { return JSON.parse(structuredText) as T; } catch { throw new Error("Groq returned text that did not match the required JSON schema."); } }

const architectureSchema = { type: "object", additionalProperties: false, required: ["overview", "modules"], properties: { overview: { type: "string" }, modules: { type: "array", minItems: 1, maxItems: 6, items: { type: "object", additionalProperties: false, required: ["name", "path", "purpose"], properties: { name: { type: "string" }, path: { type: "string" }, purpose: { type: "string" } } } } } };
const rankingSchema = { type: "object", additionalProperties: false, required: ["recommended_issues"], properties: { recommended_issues: { type: "array", maxItems: 4, items: { type: "object", additionalProperties: false, required: ["issue_number", "title", "url", "fit_score", "estimated_difficulty", "why_this_fits"], properties: { issue_number: { type: "integer" }, title: { type: "string" }, url: { type: "string" }, fit_score: { type: "string", enum: ["high", "medium"] }, estimated_difficulty: { type: "string" }, why_this_fits: { type: "string" } } } } } };

export async function POST(request: Request) { try { const body = await request.json() as Record<string, string>; const parsed = parseRepo(body.repoUrl ?? ""); if (!parsed || !body.skills?.trim() || !body.experience || !body.interest?.trim()) return NextResponse.json({ error: "Enter a GitHub repository URL and complete every field." }, { status: 400 }); const { owner, repo } = parsed;
  const repository = await github(`/repos/${owner}/${repo}`) as { default_branch: string };
  const [treeData, readme, contributing, languages, allOpenIssues] = await Promise.all([github(`/repos/${owner}/${repo}/git/trees/${repository.default_branch}?recursive=1`), content(owner, repo, "README.md"), content(owner, repo, "CONTRIBUTING.md"), github(`/repos/${owner}/${repo}/languages`), openIssues(owner, repo)]);
  const tree = (treeData.tree as { path: string; type: string }[]).filter((entry) => entry.path.split("/").length <= 3 && entry.type !== "commit").slice(0, 160).map((entry) => entry.path);
  const targetLabels = new Set(["good first issue", "help wanted"]); const issues = allOpenIssues.filter((issue) => !issue.pull_request && issue.labels.some((label) => targetLabels.has(label.name.toLowerCase()))).slice(0, 20).map((issue) => ({ number: issue.number, title: issue.title, body: clip(issue.body ?? "", 2200), labels: issue.labels.map((label) => label.name), url: issue.html_url }));
  const architecture = await groq<{ overview: string; modules: { name: string; path: string; purpose: string }[] }>("architecture_summary", architectureSchema, "Explain the codebase in plain newcomer-friendly language. Base every claim only on supplied file tree, README, and language data. If a purpose is uncertain, say so. Return 4–6 modules where possible; never invent files or details.", { file_tree: tree, readme: clip(readme, 3500), contributing: clip(contributing, 1600), languages });
  const recommendations = await groq<{ recommended_issues: { issue_number: number; title: string; url: string; fit_score: "high" | "medium"; estimated_difficulty: string; why_this_fits: string }[] }>("issue_ranking", rankingSchema, "Rank up to four best-fit issues only from the provided list. Never invent an issue, number, title, URL, module, file, or implementation detail. Ground each reason in the issue text and architecture summary. Start each reason with a concrete technical fact: module/context, skill or concept exercised, and rough scope when supported. End with one short earned encouraging sentence; never lead with encouragement. Tone calibration: 'This issue is in the layers/normalization module — you’d be adding a missing edge case to the batch-norm implementation, roughly 15–20 lines. Given your PyTorch background, this is a clean way to get your first PR into the codebase’s core math.'", { architecture, issues, user: { skills: body.skills, experience: body.experience, interest: body.interest } });
  return NextResponse.json({ architecture, recommendations });
} catch (error) { const message = error instanceof Error ? error.message : "Analysis failed."; return NextResponse.json({ error: message }, { status: 500 }); } }
